#!/usr/bin/env bash

set -euo pipefail

main() {
  local window_name="$1"
  local program="${2:-$window_name}"
  local current_session_name=$(tmux display-message -p '#S')
  local current_window_name=$(tmux display-message -p '#W')
  local runner="$XDG_CONFIG_HOME/tmux/scripts/run-with-atuin-history"

  # If already on the quick window, toggle back to last window
  [[ "$current_window_name" == "$window_name" ]] && tmux last-window && return

  # Switch to quick window or create quick window
  tmux select-window -t "$current_session_name:=$window_name" &>/dev/null ||
    tmux new-window -t "$current_session_name:" -c "#{pane_current_path}" \
      -n "$window_name" "$runner" "$program"
}

main "$@"
