#!/usr/bin/env zsh

set -euo pipefail

DEFAULT_NOTIE_DIRECTORY="${XDG_DATA_HOME:-$HOME/.local/share}/notie"

exit_with_error() {
  echo "$1" 1>&2
  exit 1
}

create() {
  local filename="$2"
  local notie_directory="$1"

  if [ -z "$filename" ]; then
    exit_with_error "No filename provided."
  fi

  local filepath="$notie_directory/$filename"
  local directory="$(dirname $filepath)"

  mkdir -p "$directory"

  nvim \
    -c "norm Gzz" \
    -c "set nowrap" \
    -c "set nonumber" \
    -c "set norelativenumber" \
    -c "set laststatus=0" \
    -c "set textwidth=100" \
    -c "set formatoptions=tq" \
    -c "set formatprg=par\ -jw100" \
    "$filepath"
}

main() {
  local notie_directory="${NOTIE_DIRECTORY:-$DEFAULT_NOTIE_DIRECTORY}"
  local filename="$(cd "$notie_directory" && \
                    fd -0 --type=f --strip-cwd-prefix | \
                    xargs -0 ls -lt | \
                    awk '{print $NF}' | \
                    fzf --exact --print-query | \
                    tail -n1 | \
                    grep -Ev '^$')"

  create "$notie_directory" "$filename"
}

main
