"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 1000

[git_branch]
symbol = ' '

[git_status]
ahead = '↑${count}'
diverged = '↑${ahead_count}↓${behind_count}'
behind = '↓${count}'
