"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 1000

[package]
disabled = true

[maven]
disabled = true

[aws]
disabled = true

[battery]
disabled = true

[git_branch]
symbol = ' '

[git_status]
disabled = false
ahead = '↑${count}'
diverged = '↑${ahead_count}↓${behind_count}'
behind = '↓${count}'
stashed=''

[hostname]
ssh_symbol = ' '
trim_at = ''

[nodejs]
symbol = ' '

[python]
symbol = ' '
generic_venv_names = ['venv', '.venv']

[ruby]
symbol = '󰴭 '
