"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 1000

[battery]
disabled = true

[git_branch]
symbol = ' '

[git_status]
disabled = false
ahead = '↑${count}'
diverged = '↑${ahead_count}↓${behind_count}'
behind = '↓${count}'
stashed=''

[hostname]
ssh_symbol = ' '
trim_at = ''

[nodejs]
symbol = ' '

[ruby]
symbol = '󰴭 '
