#!/usr/bin/zsh

# Check running containers in a compact way
alias dps="docker ps --format 'table {{.Names}}\t{{.Status}}'"

# Vim aliases
alias vi="nvim"
alias vim="nvim"

# Exa aliases
alias l='exa -l'

# Disable status bar for sxiv
alias sxiv='sxiv -b'

# Klippy aliases
alias kcp='klippy copy'
alias kpp='klippy paste'

# Joshuto alias
alias j='joshuto'

# Lazygit alias
alias g='lazygit'
