#!/usr/bin/zsh

# Check running containers in a compact way
alias dps="docker ps --format 'table {{.Names}}\t{{.Status}}'"

# Vim aliases
alias vi="nvim"
alias vim="nvim"

# Eza aliases
alias l='eza -l'

# Klippy aliases
alias kcp='klippy copy'
alias kpp='klippy paste'

# Joshuto alias
alias j='joshuto'

# Lazygit alias
alias g='lazygit'
