#!/usr/bin/zsh

# Configure Pipenv
export PIPENV_VENV_IN_PROJECT=enabled
export PIPENV_VERBOSITY=-1

# Configure IRB
export IRBRC="$XDG_CONFIG_HOME/irb/irbrc"

# Configure gemrc
export GEMRC="$XDG_CONFIG_HOME/gems/gemrc"

# Configure SQLite
export SQLITE_HISTORY="$XDG_DATA_HOME/sqlite/history"

# Configure pass
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/pass"

# Configure notie
export NOTIE_DIRECTORY="/mnt/Notes"

# Init OMZ
zstyle ':omz:*' aliases no
zstyle ':omz:plugins:bundler' aliases yes
zstyle ':omz:plugins:z' aliases yes
zstyle ':omz:update' mode disabled
export BUNDLED_COMMANDS=(good_job rails stree)
export CASE_SENSITIVE=true
export DISABLE_UPDATE_PROMPT=true
export DISABLE_MAGIC_FUNCTIONS=true
source "$ZSH/oh-my-zsh.sh"

# Init starship
export STARSHIP_LOG="error" # Disable command timeout errors
which starship &>/dev/null && eval "$(starship init zsh)"

# Enable option stacking auto completion for docker
zstyle ':completion:*:*:docker:*' option-stacking yes
zstyle ':completion:*:*:docker-*:*' option-stacking yes

compinit -d "$XDG_CACHE_HOME/zsh/zcompdump-$ZSH_VERSION"
zstyle ':completion:*' cache-path "$XDG_CACHE_HOME/zsh/zcompcache"

# Configure MISE
if which mise &>/dev/null; then
  eval "$(mise activate zsh)"
  eval "$(mise complete --shell zsh)"

  export MISE_RUBY_DEFAULT_PACKAGES_FILE="$XDG_CONFIG_HOME/mise/ruby/default_gems"
  export MISE_NODE_DEFAULT_PACKAGES_FILE="$XDG_CONFIG_HOME/mise/nodejs/default_npm_packages"
  export MISE_PYTHON_DEFAULT_PACKAGES_FILE="$XDG_CONFIG_HOME/mise/python/default_python_packages"
fi

# Add GPG key
export GPG_TTY=$(tty)

# Setup Copilot CLI
which github-copilot-cli &>/dev/null && eval "$(github-copilot-cli alias -- "$0")"

# Setup atuin
which atuin &>/dev/null && eval "$(atuin init zsh --disable-up-arrow)"

# Setup carapace
which carapace &>/dev/null && source <(carapace _carapace)

# Set catppuccin theme for fzf
export FZF_DEFAULT_OPTS=" \
--color=bg+:#313244,bg:#1e1e2e,spinner:#f5e0dc,hl:#f38ba8 \
--color=fg:#cdd6f4,header:#f38ba8,info:#cba6f7,pointer:#f5e0dc \
--color=marker:#f5e0dc,fg+:#cdd6f4,prompt:#cba6f7,hl+:#f38ba8"
