#!/usr/bin/env zsh

set -euo pipefail

NOTIE_DIRECTORY="${XDG_DATA_HOME:-$HOME/.local/share}/notie"

exit_with_error() {
  echo "$1" 1>&2
  exit 1
}

create() {
  local filename="$1"

  if [ -z "$filename" ]; then
    exit_with_error "No filename provided."
  fi

  local filepath="$NOTIE_DIRECTORY/$filename"
  local directory="$(dirname $filepath)"

  mkdir -p "$directory"

  nvim \
    -c "norm Gzz" \
    -c "set nonumber" \
    -c "set norelativenumber" \
    -c "set laststatus=0" \
    "$filepath"
}

main() {
  create "$(cd "$NOTIE_DIRECTORY" && fd --type=f --strip-cwd-prefix | sort | fzf --exact --print-query | tail -n1 | grep -Ev '^$')"
}

main
