vo=gpu-next
target-colorspace-hint=yes
gpu-api=d3d11
d3d11-adapter="NVIDIA GeForce RTX 3050 Ti Laptop GPU"

profile=high-quality
hwdec=auto-safe

save-position-on-quit=yes
loop-file=inf

osd-bar=no
cursor-autohide=1000
border=no
really-quiet=yes

volume=70
mute=yes
