#!/usr/bin/zsh

# Vim like exiting
alias :q="exit"

# Check running containers in a compact way
alias dps="docker ps --format 'table {{.Names}}\t{{.Status}}'"

# Vim aliases
alias vi="nvim"
alias vim="nvim"

# Git aliases
alias gdm='gd $(git_main_branch)'
alias gfom='gfob $(git_main_branch)'
alias gmm='gm $(git_main_branch)'

# Exa aliases
alias l='exa -l'

# Klippy aliases
alias kcp='klippy copy'
alias kpp='klippy paste'

# Unalias for sd command
alias sd &>/dev/null && unalias sd

# Unalias for t script
alias t &>/dev/null && unalias t

# Unalias rm override by OMZ
alias rm &>/dev/null && unalias rm
