#!/bin/zsh

# Check running containers in a compact way
alias dps="docker ps --format 'table {{.Names}}\t{{.Status}}'"

# Vim aliases
alias vi="nvim"
alias vim="nvim"

# Exa aliases
alias l='exa -l'

# Klippy aliases
alias kcp='klippy copy'
alias kpp='klippy paste'
