#!/usr/bin/zsh

# Check running containers in a compact way
alias dps="docker ps --format 'table {{.Names}}\t{{.Status}}'"

# Vim aliases
alias vi="nvim"
alias vim="nvim"

# Git aliases
alias gdm='gd $(git_main_branch)'
alias gfom='gfob $(git_main_branch)'

# Exa aliases
alias l='exa -l'

# Klippy aliases
alias kcp='klippy copy'
alias kpp='klippy paste'

# Unalias for t script
unalias t
