#!/usr/bin/zsh

# Configure Pipenv
export PIPENV_VENV_IN_PROJECT=enabled
export PIPENV_VERBOSITY=-1

# Configure IRB
export IRBRC="$XDG_CONFIG_HOME/irb/irbrc"

# Configure SQLite
export SQLITE_HISTORY="$XDG_DATA_HOME/sqlite/history"

# Configure ASDF
export ASDF_DIR="$XDG_STATE_HOME/asdf"
export ASDF_DATA_DIR="$XDG_DATA_HOME/asdf"
export ASDF_CONFIG_FILE="$XDG_CONFIG_HOME/asdf/asdfrc"
export ASDF_GEM_DEFAULT_PACKAGES_FILE="$XDG_CONFIG_HOME/asdf/default_gems"

# Disable OMZ characters escape on paste
export DISABLE_MAGIC_FUNCTIONS=true

# Init OMZ
source "$ZSH/oh-my-zsh.sh"

# Init p10k
source "$ZDOTDIR/.p10k.zsh"

# Enable option stacking auto completion for docker
zstyle ':completion:*:*:docker:*' option-stacking yes
zstyle ':completion:*:*:docker-*:*' option-stacking yes

compinit -d "$XDG_CACHE_HOME/zsh/zcompdump-$ZSH_VERSION"
zstyle ':completion:*' cache-path "$XDG_CACHE_HOME/zsh/zcompcache"

# Add GPG key
export GPG_TTY=$(tty)

# Fix fuzzy search (zsh-history-substring-search and zsh-vi-mode)
bindkey -v "^R" fzf-history-widget

# Set catppuccin theme for fzf
export FZF_DEFAULT_OPTS=" \
--color=bg+:#363a4f,bg:#24273a,spinner:#f4dbd6,hl:#ed8796 \
--color=fg:#cad3f5,header:#ed8796,info:#c6a0f6,pointer:#f4dbd6 \
--color=marker:#f4dbd6,fg+:#cad3f5,prompt:#c6a0f6,hl+:#ed8796"
