#!/bin/sh

set -euo pipefail

# ============================================================================ #
# ================================= CONSTANTS ================================ #
# ============================================================================ #

NOTIE_DIRECTORY="/home/raza/.local/share/notie"
NOTIE_PDF_DIRECTORY="$NOTIE_DIRECTORY/pdf"
NOTIE_MARKDOWN_DIRECTORY="$NOTIE_DIRECTORY/markdown"

TODAYS_STAMP="$(date +%Y%m%d)"

TODAYS_PDF_FILE="$NOTIE_PDF_DIRECTORY/$TODAYS_STAMP.pdf"
TODAYS_MARKDOWN_FILE="$NOTIE_MARKDOWN_DIRECTORY/$TODAYS_STAMP.md"

# ============================================================================ #
# =============================== SUB COMMANDS =============================== #
# ============================================================================ #

# ============================== COMMAND: Help =============================== #

help() {
  cat <<HELP
Usage: notie COMMAND

Commands:
  help            Show this help
  create          Create a new note entry
HELP
}

# ============================= COMMAND: Create ============================== #

create() {
  if [ ! -f "$TODAYS_MARKDOWN_FILE" ]; then
    echo "# Notes for $(date +%Y-%m-%d)" >"$TODAYS_MARKDOWN_FILE"
  fi

  nvim \
    -c "norm Go" \
    -c "norm Go## $(date +%H:%M)" \
    -c "norm G2o" \
    -c "norm zz" \
    -c "imap <C-c> <cmd>:q!<CR>" \
    -c "nmap <C-c> <cmd>:q!<CR>" \
    -c "set nonumber norelativenumber" \
    -c "set laststatus=0" \
    -c "startinsert" \
    "$TODAYS_MARKDOWN_FILE"
}

# ============================================================================ #
# ================================ ENTRYPOINT ================================ #
# ============================================================================ #

case "$1" in
create)
  create
  ;;
*)
  help
  exit 1
  ;;
esac
