#!/usr/bin/bash

set -euo pipefail

# ============================================================================ #
# ================================ CONSTANTS ================================= #
# ============================================================================ #

# ============================= Player constants ============================= #

: "${IMAGE_PLAYER:=sxiv -a}"
: "${VIDEO_PLAYER:=mpv --really-quiet --loop=inf}"

if [[ "$DESKTOP_SESSION" != "gnome" ]]; then
  IMAGE_PLAYER="devour $IMAGE_PLAYER"
  VIDEO_PLAYER="devour $VIDEO_PLAYER"
fi

# ============================= Option defaults ============================== #

: "${PLAY_ORDER:=normal}"

# ============================================================================ #
# ============================== HELPER METHODS ============================== #
# ============================================================================ #

help() {
  cat <<HELP
Usage: $(basename $0) [OPTIONS] TYPE PATH

Play media using defined programs.

Arguments:
  TYPE        Type of files to play (i[mages], v[ideos])
  PATH        Path to file or directory

Options:
  --order     Files ordering (default: normal)
              Possible values: random, size, normal
HELP
}

exit_with_error() {
  echo "$1" 1>&2
  exit 1
}

command_available() {
  command -v "$1" >/dev/null 2>&1 || exit_with_error "Please make sure $1 is installed."
}

# ============================================================================ #
# ============================= OPTIONS PARSING ============================== #
# ============================================================================ #

for option in "$@"; do
  case "$option" in
  --order=*)
    PLAY_ORDER="${1#*=}"
    shift
    ;;
  --*)
    exit_with_error "Unknown option: ${1%%=*}"
    ;;
  esac
done

# ============================================================================ #
# ================================ ENTRYPOINT ================================ #
# ============================================================================ #

command_available fd

if [[ $# -ne 2 ]]; then
  help
  exit 1
fi

PLAY_TYPE="$1"
PLAY_DIRECTORY="$2"

main() {
  case "$PLAY_TYPE" in
  i | images)
    local player="$IMAGE_PLAYER"
    local glob="**/*.{gif,jpeg,jpg,png,webp}"
    ;;
  v | videos)
    local player="$VIDEO_PLAYER"
    local glob="**/*.{mkv,mov,mp4,webm}"
    ;;
  *)
    exit_with_error "Unknown type: $PLAY_TYPE"
    ;;
  esac

  local fd="fd --glob $glob --print0 $PLAY_DIRECTORY"

  case "$PLAY_ORDER" in
  normal) local sorter="sort -z" ;;
  random) local sorter="shuf -z" ;;
  size) local sorter="xargs -0 ls -S --zero" ;;
  *) exit_with_error "Unknown --order value." ;;
  esac

  $fd | $sorter | xargs -0 $player
}

main "$@"
