#!/bin/sh

set -euo pipefail

SNAPPY_DIRECTORY="$XDG_STATE_HOME/snappy"
SNAPPY_CACHE_DIRECTORY="$XDG_CACHE_HOME/snappy"

mkdir -p "$SNAPPY_DIRECTORY"
mkdir -p "$SNAPPY_CACHE_DIRECTORY"

# Build snapshot for npm
npm list --global --depth=0 --json >"$SNAPPY_DIRECTORY/npm.json"

# Build snapshot for pacman
pacman -Qqm >"$SNAPPY_DIRECTORY/pacman.txt"

# Build snapshot for crontab
crontab -l >"$SNAPPY_DIRECTORY/crontab.txt"
