#!/bin/sh

set -eo pipefail

# ============================================================================ #
# ============================== HELPER METHODS ============================== #
# ============================================================================ #

# ============================= HELPERS: Basics ============================== #

help() {
  cat <<HELP
Usage: $(basename $0) PATH

Create or attach to dev session

Arguments:
  PATH        Path to the directory
HELP
}

exit_with_error() {
  echo "$1" 1>&2
  exit 1
}

# =============================== HELPERS: Tmux ============================== #

switch_or_attach() {
  local session="$1"

  if [ -n "$TMUX" ]; then
    tmux switch-client -t="$session"
  else
    tmux attach-session -t="$session"
  fi
}

# ============================================================================ #
# ============================= SESSION CREATORS ============================= #
# ============================================================================ #

# =========================== Dev session creator ============================ #

create_or_attach_to_dev_session() {
  local working_directory="$1"
  local session="$(basename "$working_directory")"

  [[ -d "$working_directory" ]] || exit_with_error "Directory not found."

  if tmux has-session -t="$session" 2>/dev/null; then
    switch_or_attach "$session"
  else
    tmux new-session -d -s "$session" -c "$working_directory"
    tmux rename-window -t="$session:1" "editor"
    tmux send-keys -t="$session:editor" "nvim" "C-m"
    tmux new-window -t="$session" -n "shell" -c "$working_directory"

    switch_or_attach "$session:editor"
  fi
}

# ============================================================================ #
# ================================ ENTRYPOINT ================================ #
# ============================================================================ #

if [[ $# -ne 1 ]]; then
  help
  exit 1
elif [[ "$1" == "-h" ]] && [[ "$1" == "--help" ]]; then
  help
  exit 0
fi

SESSION_NAME="$1"

if [[ -d "$SESSION_NAME" ]]; then
  create_or_attach_to_dev_session "$SESSION_NAME"
elif [[ -d "$HOME/Developer/$SESSION_NAME" ]]; then
  create_or_attach_to_dev_session "$HOME/Developer/$SESSION_NAME"
else
  exit_with_error "Don't know how to create session for: $SESSION_NAME"
fi
