#!/bin/sh

set -eo pipefail

# ============================================================================ #
# ============================== HELPER METHODS ============================== #
# ============================================================================ #

# ============================= HELPERS: Basics ============================== #

help() {
  cat <<HELP
Usage: $(basename $0) NAME

Arguments:
  NAME        Name of the tmux session
HELP
}

exit_with_error() {
  echo "$1" 1>&2
  exit 1
}

# =============================== HELPERS: Tmux ============================== #

create_session() {
  local session="$1"

  if ! tmux has-session -t="$session" 2>/dev/null; then
    tmux new-session -d -s "$session"
  fi
}

switch_or_attach() {
  local session="$1"

  if [ -n "$TMUX" ]; then
    tmux switch-client -t="$session"
  else
    tmux attach-session -t="$session"
  fi
}

# ============================================================================ #
# ============================= SESSION CREATORS ============================= #
# ============================================================================ #

# ============================== SESSION: dots =============================== #

create_or_attach_dots() {
  local session="dots"
  local working_directory="$HOME/Developer/archie"

  if tmux has-session -t="$session" 2>/dev/null; then
    switch_or_attach "$session"
  else
    tmux new-session -d -s "$session" -c "$working_directory"
    tmux rename-window -t="$session:1" "editor"
    tmux send-keys -t="$session:editor" "nvim" "C-m"
    tmux new-window -t="$session" -n "shell" -c "$working_directory"

    switch_or_attach "$session:editor"
  fi

}

# ============================= SESSION: marker ============================== #

create_or_attach_marker() {
  local session="marker"
  local working_directory="$HOME/Developer/marker"

  if tmux has-session -t="$session" 2>/dev/null; then
    switch_or_attach "$session"
  else
    tmux new-session -d -s "$session" -c "$working_directory"
    tmux rename-window -t="$session:1" "editor"
    tmux send-keys -t="$session:editor" "nvim" "C-m"
    tmux new-window -t="$session" -n "shell" -c "$working_directory"

    switch_or_attach "$session:editor"
  fi

}

# ============================== SESSION: nvim =============================== #

create_or_attach_nvim() {
  local session="nvim"
  local working_directory="$HOME/Developer/archie/config/nvim"

  if tmux has-session -t="$session" 2>/dev/null; then
    switch_or_attach "$session"
  else
    tmux new-session -d -s "$session" -c "$working_directory"
    tmux rename-window -t="$session:1" "editor"
    tmux send-keys -t="$session:editor" "nvim" "C-m"
    tmux new-window -t="$session" -n "shell" -c "$working_directory"

    switch_or_attach "$session:editor"
  fi

}

# ============================== SESSION: nukes ============================== #

create_or_attach_nukes() {
  local session="nukes"
  local working_directory="$HOME/Developer/nukes"

  if tmux has-session -t="$session" 2>/dev/null; then
    switch_or_attach "$session"
  else
    tmux new-session -d -s "$session" -c "$working_directory"
    tmux rename-window -t="$session:1" "editor"
    tmux send-keys -t="$session:editor" "nvim" "C-m"
    tmux new-window -t="$session" -n "shell" -c "$working_directory"

    switch_or_attach "$session:editor"
  fi

}

# ============================================================================ #
# ================================ ENTRYPOINT ================================ #
# ============================================================================ #

if [ $# -ne 1 ]; then
  help
  exit 1
fi

case "$1" in
--help | -h)
  help
  exit 0
  ;;
dots)
  create_or_attach_dots
  ;;
marker)
  create_or_attach_marker
  ;;
nukes)
  create_or_attach_nukes
  ;;
nvim)
  create_or_attach_nvim
  ;;
*)
  create_session "$1"
  switch_or_attach "$1"
  ;;
esac
